### ISSUE TITLE
[compat] MX Linux Debian 10 32 bit

### ISSUE THREAD

**Issue by JueGoWinDo** [hensm/fx_cast#166] opened 2021-02-13 12:15 UTC
MX Linux Debian 10 bit

Hi!
I'm trying to use your extension on Debian 32 bit, MX Linux, but It's seems don't work. I didn't find the .deb for 32 bit.
Best,
Alex

**Comment by hensm** [comment] 2021-02-14 02:47
Duplicate of #141 

I don't release 32-bit builds for Linux, since the packaging method relies on prebuilt binaries that aren't available for 32-bit Linux, but it should be relatively straightforward to build a non-packaged version yourself, provided you have a 32-bit version of Node available.

**Closed by hensm** 2021-02-14 02:47 UTC
