### ISSUE TITLE
x86 compability

### ISSUE THREAD

**Issue by Chraftingblock** [hensm/fx_cast#141] opened 2020-09-01 17:08 UTC
Hi There,
it Would be nice, if you could add x86 compatiblity toyour fx cast plugin.
Thank you for building great plugins

**Comment by rimrul** [comment] 2020-09-02 04:34
Duplicate of #88

x86 compatibility is planned for windows. IDK about mac or Linux though.

**Comment by hensm** [comment] 2020-09-02 16:13
Added 32-bit support for Windows, but no plans for macOS or Linux, since it's pretty much obsolete there.

**Closed** 2020-09-02 16:12 UTC

**Comment by Chraftingblock** [comment] 2020-09-02 19:06
OK, thank you!!!!!

**Comment by cpeterso** [comment] 2020-09-03 05:49
> Added 32-bit support for Windows, but no plans for macOS or Linux, since it's pretty much obsolete there.

FWIW, Firefox no longer supports 32-bit macOS. 😄 About 35% of Linux Firefox users run 32-bit.

**Comment by hensm** [comment] 2020-09-03 12:49
@cpeterso 
> About 35% of Linux Firefox users run 32-bit

Interesting, I'm surprised it's still that high given that distros are dropping (or trying to drop) support. Is that from telemetry data, because anecdotally, I'd guess that's disabled on a large proportion of Linux systems.

**Comment by cpeterso** [comment] 2020-09-03 19:27
> @cpeterso
> 
> > About 35% of Linux Firefox users run 32-bit
> 
> Interesting, I'm surprised it's still that high given that distros are dropping (or trying to drop) support. Is that from telemetry data, because anecdotally, I'd guess that's disabled on a large proportion of Linux systems.

35% is a rough estimate from Firefox crash reports. Many distros compile their own Firefox builds (instead of using Mozilla's official builds) and, as you said, also disable telemetry. So Mozilla doesn't have much insight into Firefox usage on Linux.

**Comment by hensm** [comment] 2020-09-03 22:43
Thanks for the info. Looks like it would be really annoying to build 32-bit Linux binaries with my current packaging method, so I'll leave it up to those users to build it themselves for now.
