### ISSUE TITLE
no streaming device found. 

### ISSUE THREAD

**Issue by leuchtrakete666** [hensm/fx_cast#120] opened 2020-06-14 19:58 UTC
when opening the extension, there is no streaming device found. while running youtube on the tv, it finds my host with youtube, but the button is greyed out.

i have a Mi Box S running with AndroidTV 9. it has a Chromecast built in with version 1.47.

thats the output of `avahi-browse -rv _googlecast._tcp`

[output_avahi-browse.txt](https://github.com/hensm/fx_cast/files/4777120/output_avahi-browse.txt)

**Comment by hensm** [comment] 2020-06-14 21:06
I've had a few issues like this, but they're all the same problem, so I'll collect them in one place to make it simpler.

Duplicate of #121

**Closed by hensm** 2020-06-14 21:06 UTC

**Comment by hensm** [comment] 2020-06-14 21:15
W.r.t your specific issue, I'll get back to you once I've done some testing myself. If Avahi itself isn't finding the devices at first, it's an Avahi problem. The button is greyed out because the UI is confusing, but it's probably because of how you're trying to cast (via the menu or toolbar button instead of an in-page cast button).
