### ISSUE TITLE
[compat] Twitch

### ISSUE THREAD

**Issue by ceiphr** [hensm/fx_cast#114] opened 2020-05-04 02:49 UTC
**App name:** Twitch
**App URL:** [twitch.tv](https://www.twitch.tv/)
**App ID (if possible):** B3DCF968

**Issues:**
Cast icon in video player is missing until I start casting from the right-click menu. Works perfectly otherwise.

FF v75.0
fx_cast/fx_cast_bridge v0.0.6
Ubuntu 19.10 (Wayland)

**Error log (if applicable):**

**Comment by hensm** [comment] 2020-05-04 04:45
Since I can't test well right now, can you just describe that behaviour a little more? Is it opening the receiver selector, clicking the cast button, or establishing a session (popup close) that causes the cast icon to appear?

**Comment by hensm** [comment] 2020-05-04 04:45
Duplicate of #44

**Comment by ceiphr** [comment] 2020-05-04 04:53
The establishing of the session caused the cast icon to appear. 

Should I bring this report into #44 and close this issue?

**Comment by hensm** [comment] 2020-05-04 06:11
That would make sense, reopened it.

Will try testing this sometime later and see if I can reproduce it. I’ve had the cast icon not show up before, but couldn’t reliably discern the cause.

**Closed** 2020-05-04 06:11 UTC
