### ISSUE TITLE
bug? only one chromecast device showing

### ISSUE THREAD

**Issue by kleajmp** [hensm/fx_cast#113] opened 2020-05-03 15:33 UTC
I have 3 chromecast audio devices and one chromecast video device in my local network (same subnet). Only one chromecast audio device is showing up in the fx_cast list. Running on Ubuntu (Mint 19.1). I tested with multiple sources (YouTube, Plex, ...) and the same chromecast device is always showing up. On my phone (android) all chromecast devices are showing.

Let me know if I can give any other info to solute the problem.

**Comment by hensm** [comment] 2020-05-03 16:26
I haven't really tested with more than one Chromecast device, but I can get several devices to appear in the receiver list with a fake mDNS advertisement.

Avahi output would be useful:
````sh
avahi-browse -rv _googlecast._tcp
````

If they show up there, it's an issue with the bridge, probably. Otherwise, it's kinda diffcult to debug discovery issues since it's usually network config-related.

**Comment by kleajmp** [comment] 2020-05-04 12:58
So there must be an issue with the bridge then...
What command can I use to restart the bridge? 
I tried to cast again just now, but now **no device is showing** in the Firefox extension.

They all do show up here:
` avahi-browse -rv _googlecast._tcp
Server version: avahi 0.7; Host name: nadia.local
E Ifce Prot Name                                          Type                 Domain
+ wlp4s0 IPv4 Google-Cast-Group-ed353f02450a433095427c43f42284ed-1 _googlecast._tcp     local
+ wlp4s0 IPv4 Google-Cast-Group-a0b5c8ad56dd4c81993844a35d3a58c8-1 _googlecast._tcp     local
+ wlp4s0 IPv4 Google-Cast-Group-55b8d9856d024b1090a693ffc466af32-1 _googlecast._tcp     local
+ wlp4s0 IPv4 Chromecast-Audio-6a2be4d62bbf0cfe313d015de791b104 _googlecast._tcp     local
+ wlp4s0 IPv4 Chromecast-Audio-71bc7e64fe41095ea880afbee5addb6c _googlecast._tcp     local
+ wlp4s0 IPv4 Chromecast-Audio-e8e9c73cb9adc2e0b32328d5b850b1b8 _googlecast._tcp     local
= wlp4s0 IPv4 Google-Cast-Group-ed353f02450a433095427c43f42284ed-1 _googlecast._tcp     local
   hostname = [6a2be4d6-2bbf-0cfe-313d-015de791b104.local]
   address = [192.168.1.100]
   port = [42360]
   txt = ["rs=" "nf=1" "bs=FA8FCA8189AB" "st=0" "ca=198692" "fn=high" "ic=/setup/icon.png" "md=Google Cast Group" "ve=05" "rm=" "cd=ed353f02-450a-4330-9542-7c43f42284ed" "id=ed353f02-450a-4330-9542-7c43f42284ed"]
= wlp4s0 IPv4 Google-Cast-Group-a0b5c8ad56dd4c81993844a35d3a58c8-1 _googlecast._tcp     local
   hostname = [6a2be4d6-2bbf-0cfe-313d-015de791b104.local]
   address = [192.168.1.100]
   port = [42904]
   txt = ["rs=" "nf=1" "bs=FA8FCA8189AB" "st=0" "ca=198692" "fn=rogezz" "ic=/setup/icon.png" "md=Google Cast Group" "ve=05" "rm=" "cd=a0b5c8ad-56dd-4c81-9938-44a35d3a58c8" "id=a0b5c8ad-56dd-4c81-9938-44a35d3a58c8"]
= wlp4s0 IPv4 Google-Cast-Group-55b8d9856d024b1090a693ffc466af32-1 _googlecast._tcp     local
   hostname = [6a2be4d6-2bbf-0cfe-313d-015de791b104.local]
   address = [192.168.1.100]
   port = [42198]
   txt = ["rs=" "nf=1" "bs=FA8FCA8189AB" "st=0" "ca=198692" "fn=bajo" "ic=/setup/icon.png" "md=Google Cast Group" "ve=05" "rm=" "cd=55b8d985-6d02-4b10-90a6-93ffc466af32" "id=55b8d985-6d02-4b10-90a6-93ffc466af32"]
= wlp4s0 IPv4 Chromecast-Audio-6a2be4d62bbf0cfe313d015de791b104 _googlecast._tcp     local
   hostname = [6a2be4d6-2bbf-0cfe-313d-015de791b104.local]
   address = [192.168.1.100]
   port = [8009]
   txt = ["rs=" "nf=1" "bs=FA8FCA8189AB" "st=0" "ca=198660" "fn=Vivarium" "ic=/setup/icon.png" "md=Chromecast Audio" "ve=05" "rm=" "cd=C79F44940BBA724F7A9AB06C1B0882FC" "id=6a2be4d62bbf0cfe313d015de791b104"]
= wlp4s0 IPv4 Chromecast-Audio-71bc7e64fe41095ea880afbee5addb6c _googlecast._tcp     local
   hostname = [71bc7e64-fe41-095e-a880-afbee5addb6c.local]
   address = [192.168.1.102]
   port = [8009]
   txt = ["rs=" "nf=1" "bs=FA8FCA8136E0" "st=0" "ca=198660" "fn=Cocina" "ic=/setup/icon.png" "md=Chromecast Audio" "ve=05" "rm=" "cd=930DC287282C5D77A473EAC22E1AB6FC" "id=71bc7e64fe41095ea880afbee5addb6c"]
= wlp4s0 IPv4 Chromecast-Audio-e8e9c73cb9adc2e0b32328d5b850b1b8 _googlecast._tcp     local
   hostname = [e8e9c73c-b9ad-c2e0-b323-28d5b850b1b8.local]
   address = [192.168.1.101]
   port = [8009]
   txt = ["rs=" "nf=2" "bs=FA8FCA8C87EE" "st=0" "ca=198660" "fn=Sosidarium" "ic=/setup/icon.png" "md=Chromecast Audio" "ve=05" "rm=" "cd=ED96CD3E8CD84C8AB9509056CDAA9B71" "id=e8e9c73cb9adc2e0b32328d5b850b1b8"]
: Cache exhausted
: All for now
`

**Comment by kleajmp** [comment] 2020-05-04 13:06
Update: I did some further testing:

- I casted some audio though my Android phone to the 'bajo' cast group, which contains 2 cast devices: Cocina and Vivarium.
- I refreshed my Plex webinterface on my Linux computer (nadia)
- Now 3 entries are discovered: 'bajo' (group), 'Cocina' (device) and 'Vivarium' (device)
So it means only playing devices are being discovered.

ps: yesterday only the 'Cocina' device was discovered by the extension, this device was also playing at that moment, also trough my Android phone.

So there must be a link I guess.

**Comment by hensm** [comment] 2020-05-04 15:23
The problem is due to the way the bridge does device discovery. Rather than using the system daemon (in your case avahi), it uses a separate implementation which only lasts the lifetime of the bridge and (clearly) isn't as reliable.

At the time I didn't want to have to build separately on each platform, especially macOS, which I didn't have access to. There are also issues with distributing Bonjour on Windows (since Windows _still_ doesn't support this natively) that I wanted to avoid.

Still, I meant to re-write the bridge as a native application a while ago, but it's kinda the perfect storm of the most annoying components to get working together cross-platform. At this point I'll just settle for calling into Avahi/Bonjour. Will need to make some changes to the way the bridge is built, though.

**Comment by hensm** [comment] 2020-05-05 20:25
Try this build:
[fx_cast_bridge-0.0.6-x64.zip](https://github.com/hensm/fx_cast/files/4583457/fx_cast_bridge-0.0.6-x64.zip)

**Comment by kleajmp** [comment] 2020-05-10 17:42
If I understand well Apple Bonjour use the same api/code as Linux Avahi (as they are the same thing with a different name?) and Windows uses a different one. The problem I have is that the bridge deamon that communicates with Avahi goes to sleep or why it stops adverting? Or what is the reason it is only adverting the active chromecast devices, does it caches them? I noticed also a strange similarity with the fx_cast_bridge and the PowerAmp app for Android. They both only detect the active/playing chromecast devices. While all my other Android apps detect all of them.

ps: I was already using "fx_cast_bridge-0.0.6-x64.deb"

**Comment by hensm** [comment] 2020-05-10 18:02
It's Bonjour on macOS and Windows, and Avahi has a compat layer for the same API. The point is that it doesn't use Avahi right now, so any discovery issues are down to that.

The build linked in the previous comment does use Avahi and it's not the same as the regular version.

**Comment by kleajmp** [comment] 2020-05-14 12:31
aha ok tnx in that case I'll try again installing it.

**Comment by kleajmp** [comment] 2020-05-16 14:25
strange enough, after installing this version, no device shows up anymore.
`systemctl is-active avahi-daemon.service
![Workspace 1_2020051616:22:28](https://user-images.githubusercontent.com/12158499/82122098-ca66ac80-9791-11ea-9e47-2d1fc64eebdc.jpg)
`

**Comment by hensm** [comment] 2020-05-17 02:55
Could be a bridge error in the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console)? Works fine for me on Windows, but I need to look into what network config I need so I can test properly in a Linux VM.

**Comment by hensm** [comment] 2020-06-14 21:06
Duplicate of #121

**Closed by hensm** 2020-06-14 21:06 UTC
